# Generated by Django 4.2.2 on 2023-06-29 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_remove_user_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("exp_date", models.DateField()),
                ("title", models.CharField(max_length=200)),
                ("vendore_code", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                (
                    "city",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.city"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=200)),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                (
                    "city",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.city",
                    ),
                ),
                (
                    "product",
                    models.ManyToManyField(
                        help_text="Select a genre for this book",
                        to="catalog.product",
                        verbose_name="product",
                    ),
                ),
            ],
        ),
    ]
