# Generated by Django 4.2.4 on 2023-08-07 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog_app", "0004_remove_comment_post_post_comments"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="post",
            name="comments",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog_app.commentmodel"
            ),
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
