# Generated by Django 4.2.4 on 2023-08-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_app", "0008_alter_comment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="approval_status",
            field=models.CharField(
                choices=[("pending", "Pending Approval"), ("approved", "Approved")],
                default="approved",
                max_length=10,
            ),
        ),
    ]
