# Generated by Django 4.2.4 on 2023-08-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_app", "0009_comment_approval_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="approval_status",
            field=models.CharField(
                choices=[("pending", "Pending Approval"), ("approved", "Approved")],
                default="pending",
                max_length=10,
            ),
        ),
    ]
