# Generated by Django 4.2.4 on 2023-08-12 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_app", "0011_post_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="post_photos/"),
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(
                default=datetime.datetime(
                    2023, 8, 12, 13, 30, 37, 456100, tzinfo=datetime.timezone.utc
                ),
                max_length=200,
            ),
            preserve_default=False,
        ),
    ]
