# Generated by Django 4.2.4 on 2023-08-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_app", "0012_post_photo_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(default="No title", max_length=200),
        ),
    ]
