# Generated by Django 4.2.4 on 2023-08-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_app", "0013_alter_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="temporary_name",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
