# Generated by Django 4.2.4 on 2023-08-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_app", "0017_post_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.CharField(default="No description", max_length=500),
        ),
    ]
